from . import mrp_mps
from . import stock_warehouse
from . import stock_location
from . import res_config_settings
from . import product_template
from . import purchase_order
from . import manufacturing
from . import hr_department
from . import emoji_logo
